# -*- coding: utf-8 -*-
"""NYERIDATASCI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11HXFIWx5NRuIGR8mBxLPr4KpI3AYgbGa
"""

pip install geopandas

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import geopandas as gpd

import matplotlib # base python plotting library
import matplotlib.pyplot as plt # submodule of matplotlib

# %matplotlib inline # to display plots, maps, charts etc in the notebook

constituents = gpd.read_file('/content/nyeri_constituents.shp') # Read in the constituents shapefile

constituents.plot() # Plot out nyeri constituents

"""**DATA** **EXPLORATION**"""

constituents.shape # find the number of columns and rows

constituents.head() # Look at the first couple of rows in our geodataframe

constituents.columns #look at all the variables included in our data

constituents['geometry'].head() # checks what geometries we have in constituents dataframe

constituents['geometry'].type.unique () #checks to make sure we only have polygons and multipolygons

constituents.plot ()

?constituents.plot

constituents.plot(figsize=(6,9))

"""**QUERYING** **DATA**"""

constituents['CONSTITUEN'].values # view all constituent names in our dataset

constituents

Nyeri_Town =constituents.loc[constituents['CONSTITUEN'] == 'NYERI TOWN'].copy().reset_index(drop=True)

Nyeri_Town.plot() # Plot the newly subsetted geodataframe

"""**dynamic** **plots** o**f one or more constituents without s**ave to a new gdf """

other_area_constituents=['KIENI','MATHIRA']
constituents.loc[constituents['CONSTITUEN'].isin(other_area_constituents)].plot()

Nyeri_Town.to_file('/content/Nyeri_Town.shp')



